# Usage: FROM [image name]
FROM rabbitmq:latest

# Usage: MAINTAINER [name]
MAINTAINER abilgin

CMD rabbitmq-server

# add user with password
CMD rabbitmqctl add_user newsgac 1234
# add virtual host 'newsgac_vhost'
CMD rabbitmqctl add_vhost newsgac_vhost
# add user tag 'jimmy_tag' for user 'jimmy'
CMD rabbitmqctl set_user_tags newsgac newsgac_tag
# set permission for user 'jimmy' on virtual host 'jimmy_vhost'
CMD rabbitmqctl set_permissions -p /newsgac_vhost newsgac ".*" ".*" ".*"

