apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: database-claim0
  annotations:
    volume.beta.kubernetes.io/storage-class: "longhorn"
  name: database-claim1
  namespace: newsgac
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
