apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frog
  name: frog
  namespace: newsgac
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: frog
        name: frog
    spec:
      containers:
        - args:
            - bash
            - -c
            - frog -S 12345 --skip p
          image: registry.diginfra.net/proycon/lamachine:newsgac
          resources:
            limits:
              cpu: 1000m
              memory: 3000Mi
            requests:
              cpu: 1000m
              memory: 3000Mi
          name: frog
          ports:
            - containerPort: 12345
      hostname: frog
      restartPolicy: Always



