apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
  namespace: newsgac
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis
        name: redis
    spec:
      containers:
      - image: redis:7.0.4
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 250Mi
        name: redis
        ports:
        - containerPort: 6379
        - containerPort: 6380
      hostname: redis
      restartPolicy: Always
