__author__ = 'abilgin'

COLLECTION = "configurations"

# SUPPORT VECTOR CLASSIFIER DEFAULTS
SVC_DEFAULT_KERNEL = 'rbf'
SVC_DEFAULT_PENALTY_PARAMETER_C = 1.0
SVC_DEFAULT_PROBABILITY = False
SVC_DEFAULT_RANDOM_STATE = None

# DECISION TREE DEFAULTS
DT_DEFAULT_CRITERION = "gini"
DT_DEFAULT_SPLITTER = "best"
DT_DEFAULT_MIN_SAMPLES_SPLIT = 2
DT_DEFAULT_MIN_SAMPLES_LEAF = 1
DT_DEFAULT_MAX_FEATURES = None
DT_DEFAULT_RANDOM_STATE = None