__author__ = 'abilgin'

COLLECTION = "configurations"

# SUPPORT VECTOR CLASSIFIER DEFAULTS
SVC_DEFAULT_KERNEL = 'linear'
SVC_DEFAULT_PENALTY_PARAMETER_C = 1.0
SVC_DEFAULT_RANDOM_STATE = 42

# DECISION TREE DEFAULTS
DT_DEFAULT_CRITERION = "gini"
DT_DEFAULT_SPLITTER = "best"
DT_DEFAULT_MIN_SAMPLES_SPLIT = 2
DT_DEFAULT_MIN_SAMPLES_LEAF = 1
DT_DEFAULT_MAX_FEATURES = None
DT_DEFAULT_RANDOM_STATE = 42

# RANDOM FOREST DEFAULTS
RF_DEFAULT_N_ESTIMATORS = 10
RF_DEFAULT_CRITERION = 'gini'
RF_DEFAULT_MAX_FEATURES = 'auto'
RF_DEFAULT_RANDOM_STATE = 42

# NAIVE BAYES DEFAULTS
NB_DEFAULT_ALPHA = 0.1
MLP_DEFAULT_ALPHA = 0.1

# XGBoost DEFAULTS
XGB_DEFAULT_N_ESTIMATORS = 100
XGB_DEFAULT_MAX_DEPTH = 3
XGB_DEFAULT_RANDOM_STATE = 42