FROM newsgac_docker_dev_worker:latest

MAINTAINER abilgin

# The WORKDIR directive is used to set where the command defined with CMD is to be executed.
WORKDIR /flask/src

EXPOSE 5000
ENTRYPOINT ["/flask/entrypoint.sh"]

CMD ["python", "app.py"]
